In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [4]:
A=np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


python -c "import numpy; numpy.info(numpy.add)"

Type this in terminal

In [5]:
B=np.zeros(10)
B[4]=1
print(B)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
C=np.arange(10,50)

In [7]:
print(C)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
A=np.arange(10)
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
A=np.arange(1,10).reshape(3,3)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
A=np.eye(3)

In [11]:
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
A=np.random.random((3,3,3))
print(A)

[[[0.27225699 0.5147585  0.33663768]
  [0.93659548 0.37871008 0.13165678]
  [0.50362412 0.97765724 0.60722048]]

 [[0.67597171 0.0062179  0.10173504]
  [0.19088648 0.06988246 0.89491505]
  [0.00919303 0.27639688 0.98266402]]

 [[0.73452768 0.79014793 0.52349169]
  [0.21013178 0.80753982 0.73436956]
  [0.64082995 0.19579465 0.23559428]]]


In [13]:
A=np.random.random((3,3))
Amax,Amin=A.max(),A.min()
print(A)
print(Amax,Amin)

[[0.02534346 0.53158517 0.02460069]
 [0.13111842 0.66507364 0.77064606]
 [0.69838452 0.22340754 0.38633573]]
0.7706460634468951 0.024600689759561645


In [14]:
A=np.random.random(30)
Amean=A.mean()
print(A)
print(Amean)

[0.38269179 0.36428652 0.78257057 0.30410243 0.34307707 0.20212572
 0.14667279 0.94336818 0.52950279 0.81662701 0.02386905 0.61455228
 0.01266387 0.39304796 0.57103171 0.88149645 0.92981576 0.59521429
 0.3206673  0.1577551  0.10989968 0.68769342 0.80627672 0.86385936
 0.61624325 0.13269853 0.8882617  0.57499138 0.89308543 0.11058913]
0.49995790861265005


In [15]:
A=np.ones((5,5))
A[1:-1,1:-1]=0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
print(0*np.nan)

nan


In [17]:
print(np.nan==np.nan)

False


In [18]:
print(np.inf>np.nan)

False


In [19]:
print(np.nan-np.nan)

nan


In [20]:
print(0.3==3*0.1)

False


In [27]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
Z=np.ones((8,8),dtype=int)
Z[1::2,::2]=0
Z[::2,1::2]=0
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [35]:
Z=np.random.random((6,7,8))
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [43]:
A=np.array([[0,1],[1,0]])
Z=np.tile(A,(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
A=np.random.random((5,5))
print(A)
Amax,Amin=A.max(),A.min()
A=(A-Amin)/(Amax-Amin)
print(A)

[[0.08541739 0.30682008 0.64274018 0.73272152 0.82305379]
 [0.3794361  0.90642604 0.37737982 0.75296306 0.8980738 ]
 [0.55997613 0.11543975 0.82693429 0.22461316 0.52435214]
 [0.18732898 0.39430729 0.11367519 0.00551735 0.21078161]
 [0.56873039 0.0754322  0.73296221 0.94160906 0.0831533 ]]
[[0.08535492 0.32187309 0.68072693 0.77685141 0.8733508 ]
 [0.39944671 0.96241499 0.39725004 0.79847488 0.95349253]
 [0.59231246 0.11742695 0.87749622 0.23405378 0.55425636]
 [0.19422416 0.41533318 0.11554192 0.         0.21927793]
 [0.60166438 0.07468803 0.77710854 1.         0.08293627]]


In [48]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

In [54]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [57]:
A=np.ones((5,3))
B=np.random.random((3,2))
C=np.dot(A,B)
print(C)

[[1.39580015 0.98809418]
 [1.39580015 0.98809418]
 [1.39580015 0.98809418]
 [1.39580015 0.98809418]
 [1.39580015 0.98809418]]


In [62]:
A=np.arange(11)
A[(3<A) & (A<=8)]*=-1
print(A)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [63]:
print(sum(range(5),-1))
from numpy import *
print(sum(np.range(5),-1))

9
10


In [64]:
print(range(5),-1)

range(0, 5) -1


In [65]:
print(sum(np.range(5),-1))

AttributeError: module 'numpy' has no attribute 'range'

In [66]:
print(sum(range(5),initial=-1))

9


In [67]:
Z=np.arange(3)
print(Z**Z)

[1 1 4]


In [68]:
print(2<<Z>>2)

[0 1 2]


In [69]:
print(Z<-Z)

[False False False]


In [70]:
print(1j*Z)

[0.+0.j 0.+1.j 0.+2.j]


In [73]:
print(Z/1/1)

[0. 1. 2.]


In [75]:
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [76]:
np.array(0)//np.array(0)

0

In [77]:
np.array(0)//np.array(0.)

nan

In [78]:
np.array(0)/np.array(0)

nan

In [79]:
np.array(0)/np.array(0.)

nan

In [80]:
Z=np.random.uniform(-10,+10,10)
print(Z)

[-8.0550897   5.18993897  4.70461449 -8.48536794 -3.75776187 -1.63303682
 -1.45219201  1.22500714 -9.73635192 -9.84180447]


In [84]:
C=np.trunc(Z+np.copysign(0.5,Z))
print(C)

[ -8.   5.   5.  -8.  -4.  -2.  -1.   1. -10. -10.]


In [85]:
Z=np.random.uniform(0,10,10)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[5. 8. 9. 7. 0. 6. 8. 3. 4. 5.]
[5. 8. 9. 7. 0. 6. 8. 3. 4. 5.]
[5. 8. 9. 7. 0. 6. 8. 3. 4. 5.]
[5 8 9 7 0 6 8 3 4 5]
[5. 8. 9. 7. 0. 6. 8. 3. 4. 5.]


In [86]:
Z=np.zeros((5,5))
Z=Z+np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [95]:
def generate():
    for i in range(10):
        yield i
Z=np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [98]:
Z=np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [99]:
Z=random.random(10)
Z.sort()
print(Z)

[0.41931759 0.42169024 0.57170389 0.59947691 0.73367645 0.77427099
 0.78907432 0.86208032 0.87043996 0.87696384]


In [100]:
import time
start=time.time()
Z=np.arange(10)
print(Z.sum())
end=time.time()
print(end-start)


45
0.0013790130615234375


In [101]:
import time
start=time.time()
Z=np.arange(10)
print(np.add.reduce(Z))
end=time.time()
print(end-start)

45
0.000400543212890625


In [103]:
A=np.random.randint(10)
B=np.random.randint(10)
equal=np.allclose(A,B)
print(equal)
print(A==B)

False
False


In [104]:
Z=np.zeros(10)
Z.flags.writeable=False
Z[0]=1

ValueError: assignment destination is read-only

In [106]:
A=np.random.random((10,2))
X,Y=A[:,0],A[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan(Y,X)
print(R)
print(T)

[0.86812119 1.02073304 0.6367919  0.89167057 0.54965717 0.91885178
 0.97358144 1.31663855 0.13628689 0.36004536]
[0.55750734 0.31111364 0.1726431  0.68198041 0.43913824 0.16922338
 0.66975142 0.72909304 0.12775145 0.19156163]


In [107]:
A=np.random.random(10)
print(A)
A[np.argmax(A)]=0
print(A)

[0.70760323 0.72488664 0.70773036 0.84633407 0.69148545 0.09619548
 0.81475277 0.90470843 0.15128344 0.08338223]
[0.70760323 0.72488664 0.70773036 0.84633407 0.69148545 0.09619548
 0.81475277 0.         0.15128344 0.08338223]


In [108]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [109]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [111]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
